### ISSUE TITLE
Add "Send now" feature for notifications

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/psp-scheduled-notifications#2] opened 2018-01-26 14:01 UTC
In the context of each email, it would be cool to be able to just hit a send now button.

**Comment by d4mation** [comment] 2019-05-13 12:34
#24 is technically a duplicate of this Issue, but I'm going to close this one instead as #24 has more details on potential implementation.

**Closed by d4mation** 2019-05-13 12:34 UTC
Labels: enhancement
